---
title: "Bi-Archetypal Analysis"
description: >
  Learn how to get started with the basics of bi-archetypal analysis.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bi-Archetypal Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, child="children/SETTINGS-knitr.txt"}
```

## Introduction

Let $X$ be a $n\times m$ matrix, ...


## Toy example


### Parameters

```{r}
set.seed(1234)

m = 50
n = 100
k = 3
c = 3
```


### Data

```{r}
ax = 1:30; ay = 1:15
bx = 31:70; by = 16:30

data = matrix(runif(n * m, -1, 1), nrow = n, ncol = m)
data[ax, ay] = rnorm(length(ax) * length(ay), mean = -0.5, sd = 0.3)
data[bx, by] = rnorm(length(bx) * length(by), mean = 0.5, sd = 0.3)

image(data, xaxt= "n", yaxt= "n")
```


#### Shuffled data

```{r}
srows = sample(n, n)
scols = sample(m, m)
sdata = data[srows, scols]

image(sdata, xaxt= "n", yaxt= "n")
```

### Archetypes

```{r}
arch = biaa::biaa(sdata, k = k, c = c, nrep = 5, maxiter = 100000)
```

#### Plot RSS
```{r}
biaa::rssplot(arch)
```

```{r}
par(mfrow = c(1, 2))
biaa:::rssplot(arch, phi = 0, theta = -180)
biaa:::rssplot(arch, phi = 0, theta = 90)
```

#### Select desired model
```{r}
barch = biaa::getmodel(arch, k = 3, c = 3)
```

### Results

```{r}
barch$rss
barch$archetypes
```

#### Clustering data using the archetypes

```{r}
library(dplyr)
malphas = tibble(ind = 1:n, clust=apply(barch$alphas, 1, which.max), sim=apply(barch$alphas, 1, max))
malphas = arrange(malphas, clust, desc(sim))
malphas = filter(malphas, sim > 0.6)
table(malphas$clust)
orows = malphas$ind

mgammas = tibble(ind = 1:m, clust=apply(barch$gammas, 2, which.max), sim=apply(barch$gammas, 2, max))
mgammas = arrange(mgammas, clust, desc(sim))
mgammas = filter(mgammas, sim > 0.6)
table(mgammas$clust)
ocols = mgammas$ind

image(sdata[orows, ocols], xaxt= "n", yaxt= "n")
```