---
title: "Bi-Archetypal Analysis"
description: >
  Learn how to get started with the basics of bi-archetypal analysis.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bi-Archetypal Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, child="children/SETTINGS-knitr.txt"}
```

## Introduction

Let $X$ be a $n\times m$ matrix, ...


## Toy example

```{r}

set.seed(2020)

n <- 100
m <- 100

rotate <- function(x) t(apply(x, 2, rev))
```

## Toy data

```{r}
ax <- 1:(n/2); ay <- (m/2+1):m;
bx <- (n/2+1):n; by <- 1:(m/2);

data <- array(0.5, dim = c(n, m))
data[ax, ay] = 0
data[bx, by] = 1

data <- data + array(rnorm(n * m, 0, 0.2), dim = c(n, m))

image(rotate(data), axes=FALSE)
```

### Shuffling data

```{r}
shuf_rows <- sample(n, n)
shuf_cols <- sample(m, m)
shuf_data <- data[shuf_rows, shuf_cols]

image(rotate(shuf_data), axes=FALSE)
```

## Bi-Archetypal analysis

```{r}
k <- 1:4
c <- 1:4

arch <- biaa::biaa(shuf_data, k, c, nrep = 5, maxiter = 5000)
```

### Ploting the RSS
```{r}
biaa::rssplot(arch)
```
```{r}
par(mfrow = c(1, 2))
biaa:::rssplot(arch, phi = 0, theta = -180)
biaa:::rssplot(arch, phi = 0, theta = 90)
```

### Geting the best model

```{r}
barch <- biaa::getmodel(arch, k = 2, c = 2)
```

## Results

```{r}
barch$rss
barch$archetypes
```

### Ordering data using the bi-archetypes

```{r}
maxalphas <- apply(barch$alphas, 1, which.max)
ord_rows <- order(maxalphas)

maxgammas <- apply(barch$gammas, 2, which.max)
ord_cols <- order(maxgammas)

image(rotate(shuf_data[ord_rows, ord_cols]), axes = FALSE)
```